# Generated by Django 4.2.4 on 2023-08-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
